-- M0 core relational schema for builder persistence.
-- Scope: users, projects, sessions, artifacts, messages, events.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.app_users (
  id text primary key,
  email text not null unique,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references public.app_users(id) on delete cascade,
  title text not null,
  framework text not null default 'nextjs',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint projects_framework_nonempty_check check (char_length(trim(framework)) > 0),
  constraint projects_id_user_id_key unique (id, user_id)
);

create table if not exists public.builder_sessions (
  id text primary key,
  project_id uuid not null,
  user_id text not null,
  preview_url text not null,
  status text not null default 'ready',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint builder_sessions_status_check check (status in ('ready', 'running', 'error')),
  constraint builder_sessions_project_owner_fkey
    foreign key (project_id, user_id)
    references public.projects(id, user_id)
    on delete cascade
);

create table if not exists public.project_artifacts (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  path text not null,
  summary text not null,
  position integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint project_artifacts_position_nonnegative_check check (position >= 0),
  constraint project_artifacts_project_path_key unique (project_id, path)
);

create table if not exists public.session_messages (
  id text primary key,
  session_id text not null references public.builder_sessions(id) on delete cascade,
  role text not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint session_messages_role_check check (role in ('user', 'assistant', 'system'))
);

create table if not exists public.session_events (
  id text primary key,
  session_id text not null references public.builder_sessions(id) on delete cascade,
  type text not null,
  level text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint session_events_level_check check (level in ('info', 'warning', 'error'))
);

create index if not exists projects_user_id_created_at_idx
  on public.projects (user_id, created_at desc);

create index if not exists builder_sessions_user_id_created_at_idx
  on public.builder_sessions (user_id, created_at desc);

create index if not exists builder_sessions_project_id_idx
  on public.builder_sessions (project_id);

create index if not exists project_artifacts_project_id_position_idx
  on public.project_artifacts (project_id, position);

create index if not exists session_messages_session_id_created_at_idx
  on public.session_messages (session_id, created_at);

create index if not exists session_events_session_id_created_at_idx
  on public.session_events (session_id, created_at);

drop trigger if exists set_app_users_updated_at on public.app_users;
create trigger set_app_users_updated_at
before update on public.app_users
for each row
execute function public.set_updated_at();

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row
execute function public.set_updated_at();

drop trigger if exists set_builder_sessions_updated_at on public.builder_sessions;
create trigger set_builder_sessions_updated_at
before update on public.builder_sessions
for each row
execute function public.set_updated_at();

drop trigger if exists set_project_artifacts_updated_at on public.project_artifacts;
create trigger set_project_artifacts_updated_at
before update on public.project_artifacts
for each row
execute function public.set_updated_at();

alter table public.app_users enable row level security;
alter table public.projects enable row level security;
alter table public.builder_sessions enable row level security;
alter table public.project_artifacts enable row level security;
alter table public.session_messages enable row level security;
alter table public.session_events enable row level security;

drop policy if exists app_users_service_role_all on public.app_users;
create policy app_users_service_role_all
on public.app_users
for all
to service_role
using (true)
with check (true);

drop policy if exists projects_service_role_all on public.projects;
create policy projects_service_role_all
on public.projects
for all
to service_role
using (true)
with check (true);

drop policy if exists builder_sessions_service_role_all on public.builder_sessions;
create policy builder_sessions_service_role_all
on public.builder_sessions
for all
to service_role
using (true)
with check (true);

drop policy if exists project_artifacts_service_role_all on public.project_artifacts;
create policy project_artifacts_service_role_all
on public.project_artifacts
for all
to service_role
using (true)
with check (true);

drop policy if exists session_messages_service_role_all on public.session_messages;
create policy session_messages_service_role_all
on public.session_messages
for all
to service_role
using (true)
with check (true);

drop policy if exists session_events_service_role_all on public.session_events;
create policy session_events_service_role_all
on public.session_events
for all
to service_role
using (true)
with check (true);
